# Generated by Django 4.1.1 on 2022-10-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbs_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=25)),
                ('c_address', models.CharField(max_length=100)),
                ('cph_no', models.IntegerField()),
                ('c_email', models.CharField(max_length=50)),
                ('c_passwd', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=25)),
                ('ph_no', models.IntegerField()),
                ('feedback', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='feedback_response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('response', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='gasrefill_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=25)),
                ('c_address', models.CharField(max_length=100)),
                ('cph_no', models.IntegerField()),
                ('c_email', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='staff_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=25)),
                ('s_address', models.CharField(max_length=100)),
                ('s_ph_no', models.IntegerField()),
                ('s_email', models.CharField(max_length=50)),
                ('s_passwd', models.CharField(max_length=25)),
            ],
        ),
    ]
