# Generated by Django 4.1.1 on 2022-10-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbs_app', '0002_customer_details_feedback_feedback_response_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.CharField(max_length=255)),
                ('u_username', models.CharField(max_length=255)),
                ('mobile_no', models.IntegerField()),
                ('user_type', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('u_password', models.CharField(max_length=255)),
                ('confirm_password', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='customer_details',
        ),
        migrations.RemoveField(
            model_name='adminlogin',
            name='user_type',
        ),
    ]
