# Generated by Django 4.1.1 on 2022-10-24 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gbs_app', '0003_user_details_delete_customer_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_details',
            old_name='user_type',
            new_name='usertype',
        ),
    ]
