# Generated by Django 4.1.1 on 2022-10-24 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gbs_app', '0004_rename_user_type_user_details_usertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_details',
            old_name='u_username',
            new_name='mail',
        ),
    ]
