# Generated by Django 4.1.1 on 2022-11-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbs_app', '0008_remove_gasrefill_booking_c_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasrefill_booking',
            name='cylinder',
            field=models.IntegerField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
