# Generated by Django 4.1.1 on 2022-11-07 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gbs_app', '0009_gasrefill_booking_cylinder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gasrefill_booking',
            old_name='c_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='gasrefill_booking',
            old_name='c_name',
            new_name='name',
        ),
    ]
