# Generated by Django 4.1.1 on 2022-11-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbs_app', '0010_rename_c_email_gasrefill_booking_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasrefill_booking',
            name='cylinder',
            field=models.CharField(max_length=100),
        ),
    ]
