# Generated by Django 4.1.1 on 2022-11-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbs_app', '0011_alter_gasrefill_booking_cylinder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='confirm_password',
        ),
        migrations.AlterField(
            model_name='user_details',
            name='mail',
            field=models.EmailField(max_length=255),
        ),
    ]
