# Generated by Django 4.1.1 on 2022-11-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbs_app', '0012_remove_user_details_confirm_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.IntegerField()),
            ],
        ),
    ]
